name: 'Tour Divide 2016 '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24495
title: 'Documenting my journey to the Tour Divide in 2016 '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#dadcdb'
    - '#485829'
    - '#b8b9bb'
    - '#ffffff'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
