name: 'Tour Divide 2016 '
favicon: null
layout_spectrum: 0.3266753740608692
typography_spectrum: 0.993731239810586
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.32628534571267664
  lightness: 0.21137044462375343
  saturation: 0.6619251847732812
  rhythmicContrast: 0.5891525219194591
purpose: []
